# Site settings
title: Ian Mouzon's Blog
email: imouzon@iastate.edu
description: "SAS"
baseurl: "/"
url: "http://mysite.org"
twitter_username: imouzon
github_username: imouzon
disqus_username: false
isso_domain: isso_domain is given as comments.mysite.org

# Build settings
markdown: redcarpet
permalink: /:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
