<!DOCTYPE html>
<html>
   <head>
      <link href ="www/css/stat105.css" type="text/css" rel = "stylesheet">
      <style type="text/css">
      @import url(https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic);
      @import url(https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz);
      @import url(https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700,400italic);
      </style>

      <title>STAT 105: Lecture 5</title>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
      <meta name="keywords" content="statistics,engineering,stat105,iastate"/>
      <meta name="description" content="Lecture 5: Graphs, etc."/>
      <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"> </script>
   </head>
   <body>
   <textarea id="source">

name: inverse
layout: true
class: center, middle, inverse
---
# STAT 105: Lecture 5
## Chapter 3: Elementary Descriptive Statistics
.footnote[Course page: [imouzon.github.io/stat105](https://imouzon.github.io/stat105)]
---
# Continuing
---
layout:false
.left-column[
## Univar. Summary
### Simple Graphs
### Freq Tables
### Histograms
### Center Stats
]
.right-column[
##Tabular Summarizing Univariate Date
```
              Group 1             Group 2
            74 79 77 81         65 77 78 74
            68 79 81 76         76 73 71 71
            81 80 80 78         86 81 76 89
            88 83 79 91         79 78 77 76
            79 75 74 73         72 76 75 79    
```

<!--- : R code (No Results in Document) -->
```{r}

   grp1 <- c(74, 79, 77, 81, 68, 79, 81, 76, 81, 80, 80, 78, 88, 83, 79, 91, 79, 75, 74, 73)
   
```

## Statistics of Location and Central Tendency

-  Mean: think of it as an equal division of the total

   -  each value in the data is an "\\(x_i\\)" (\\(i\\) is a **subscript**)

   -  Group 1: \\(x\_1 = 74, x\_2 = 79, ..., x\_{20} = 73\\)

   -  The sum: \\(x\_1 + x\_2 + x\_3 + ... + x\_{20}\\)

   -  divides : \\((x\_1 + x\_2 + x\_3 + ... + x\_{20})/20\\)

   -  Or using summation notation: \\(\frac{1}{20} \sum_{i = 1}^{20} x_i\\)
]
---
layout:false
.left-column[
## Univar. Summary
### Simple Graphs
### Freq Tables
### Histograms
### Center Stats
]
.right-column[
##Tabular Summarizing Univariate Date
```
              Group 1             Group 2
            74 79 77 81         65 77 78 74
            68 79 81 76         76 73 71 71
            81 80 80 78         86 81 76 89
            88 83 79 91         79 78 77 76
            79 75 74 73         72 76 75 79    
```

## Statistics of Location and Central Tendency

-  Mean: \\( \frac{1}{n} \sum_{i=1}^{n} x_i \\)

-  Median

-  Mode

-  Quantiles (min, Q1, Q2, Q3, max) 
]
---
.left-column[
## Univar. Summary
### Simple Graphs
### Freq Tables
### Histograms
### Center Stats
### Spread Stats
]
.right-column[
##Tabular Summarizing Univariate Date
```
              Group 1             Group 2
            74 79 77 81         65 77 78 74
            68 79 81 76         76 73 71 71
            81 80 80 78         86 81 76 89
            88 83 79 91         79 78 77 76
            79 75 74 73         72 76 75 79    
```

## Measures of Variablity (or "Spread")

-  Range

-  Interquartile Range (IQR)

]
---
.left-column[
## Univar. Summary
### Simple Graphs
### Freq Tables
### Histograms
### Center Stats
### Spread Stats
]
.right-column[
##Tabular Summarizing Univariate Date
```
              Group 1             Group 2
            74 79 77 81         65 77 78 74
            68 79 81 76         76 73 71 71
            81 80 80 78         86 81 76 89
            88 83 79 91         79 78 77 76
            79 75 74 73         72 76 75 79    
```

## Measures of Variablity (or "Spread")

** Variance and Standard Deviation **

-  Sample Variance: \\( \frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})^2 \\)

-  Sample Standard Deviation: \\( \sqrt{\frac{1}{n-1}\sum_{i=1}^{n}(x_i - \bar{x})^2} \\)

-  Population Variance: \\( \frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2 \\)

-  Population Standard Deviation: \\( \sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2} \\)
]
---
.left-column[
## Univar. Summary
### Simple Graphs
### Freq Tables
### Histograms
### Center Stats
### Spread Stats
]
.right-column[
##Tabular Summarizing Univariate Date
```
              Group 1             Group 2
            74 79 77 81         65 77 78 74
            68 79 81 76         76 73 71 71
            81 80 80 78         86 81 76 89
            88 83 79 91         79 78 77 76
            79 75 74 73         72 76 75 79    
```

## Boxplots

A simple plot making use of 

-  spread (with IQR, range, etc.)

and

-  location statistics (min, median, max, etc.)
]






      </textarea>
      <script>
         var slideshow = remark.create();
      </script>
      <script src="https://gnab.github.io/remark/downloads/remark-latest.min.js" type="text/javascript"></script>
      <script type="text/javascript">
         var hljs = remark.highlighter.engine;
      </script>
      <script src="./remark.language.js" type="text/javascript"></script>
      <script type="text/javascript">
         var slideshow = remark.create({
            highlightStyle: 'monokai',
            highlightLanguage: 'remark'
         }) ;
      </script>
   </body>
</html>
